[build]
  command = "npx @netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18.20.4"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production" 